### ISSUE TITLE
[8.0] product_variant_cost_price computation fails with average cost_method

### ISSUE THREAD

**Issue by RoelAdriaans** [OCA/product-variant#16]
The costprice seems to be divided by number of variants..

Settings
- Dutch accounting, anglo saxon accounting module installed
- Product type set to Stockable,  
- Costing Method set to average cost, 
- Inventory Valuation: Realtime 

Steps to reproduce:
- Create One product (iMac)
- Create Two variants (Quality New, Quality Refurbished)
- Create one Purchase order, different prices for both products, one 100 euro, one 25 euro
- Receive products

Result: 
Costprice on the first product is 100 euro, this is expected.
Costprice on the second product is 12.50 euro, expected amount is 25 euro. 

For an video, see https://www.youtube.com/watch?v=Xef1A3wxYKU

**Comment by RoelAdriaans** [comment]
Seems to be related to https://github.com/odoomrp/odoomrp-wip/issues/627

**Comment by pedrobaeza** [comment]
The video has been published as private.

**Comment by rafaelbn** [comment]
@RoelAdriaans-B-informed could you make video public please?

![16-12-2015 18-50-06](https://cloud.githubusercontent.com/assets/8736623/11849008/e93b0dea-a425-11e5-8d12-9d8451191e88.png)

cc @oihane @JavierIniesta @JMODaERP

**Comment by pedrobaeza** [comment]
I'm able to reproduce the problem. No need of anglo-saxon accounting nor real time inventory accounting. The problem is on the method that sets the price, that takes the total quantity of the template, not the product: https://github.com/odoo/odoo/blob/9.0/addons/stock_account/stock_account.py#L392

We should override this method to fix this, and thus depends on stock_account. Do you prefer a separate module or all together depending on both modules?

**Comment by RoelAdriaans** [comment]
Video has been made public, sorry. And, wrong button, not closed... Time for dinner... :)

**Comment by RoelAdriaans** [comment]
I have just added a commit for this, https://github.com/RoelAdriaans-B-informed/product-variant/commit/0f255ed952663e9b013defa6074e75f3dd5f5998

Can't make a valid test case, because the test case I use requires purchase orders, and this module doesn't depend on the purchase module.. Creating the same from stock.picking doesn't seem to make the right financial transactions, and i'm too limited in time to test this fully,

**Comment by pedrobaeza** [comment]
We should try to make a patch that doesn't overwrite the full method. My guess is that you overwrite the method, and call super with a context key providing the product id. That context key is used on the search method of the cost price for getting the product one instead of the template. That can be done overriding the **get_item** of the product.template. It's similar to what I have done on product_supplierinfo_for_customer module: 

https://github.com/OCA/product-attribute/blob/8.0/product_supplierinfo_for_customer/models/product_pricelist.py#L15
https://github.com/OCA/product-attribute/blob/8.0/product_supplierinfo_for_customer/models/product_supplierinfo.py#L32

About the test, you can call directly the method involved in the update with test data and check if the updated value are correct.

**Comment by rafaelbn** [comment]
cc @antespi @JavierIniesta @JMODaERP
